### ISSUE TITLE
Add test suites from other projects

### ISSUE THREAD

**Issue by paraseba** [earth-mover/icechunk#445]
Arraylake + Zarr3 + Xarray test suites (probably create subtasks for these)

- [x] Zarr stateful tests (#437, #466)
- [x] Zarr property tests
- [x] Xarray backend tests (#423)
- [x] AL stateful tests (in progress, #453)
- [ ] AL `test_stateful_history_rewrite`
